### ISSUE TITLE
The process of camera capturing images

### ISSUE THREAD

**Issue by xjd-xjd** [freerafiki/PlenopticToolbox2.0#14]
I saw in the sample that the program is about calculating depth disparity, etc. In your database, I only saw the images obtained by the existing multi-focus camera, but not the process of obtaining images. Can you provide a program for a multi-focus light field camera to obtain scene images?

**Comment by xjd-xjd** [comment]
> I saw in the sample that the program is about calculating depth disparity, etc. In your database, I only saw the images obtained by the existing multi-focus camera, but not the process of obtaining images. Can you provide a program for a multi-focus light field camera to obtain scene images?

Sorry,I found it.

**Comment by freerafiki** [comment]
great :) I close this issue then
